name: CI Pipeline

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create .env file
      run: |
        echo "SECRET_KEY=django-insecure-qp^%@n77+ydr-auroxk&zcg&xhj2x4+&3@f+!s3+m9ss*cez3j" >> .env
        echo "DEBUG=False" >> .env
        echo "POSTGRES_DB=task_management" >> .env
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=12Facebook@6" >> .env
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_PORT=5432" >> .env
      # working-directory: backend-assessment/task_management/backend
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend-assessment/task_management/backend

    # Uncomment and modify the following block to run tests
    # - name: Run Tests
    #   run: |
    #     export $(grep -v '^#' .env | xargs -d '\n')
    #     pytest
    #   working-directory: backend-assessment/task_management/backend
    #   env:
    #     ENV_FILE_PATH: .env
